apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "uni-resolver-driver-did-echo.fullname" . }}-env
  labels:
    app: {{ template "uni-resolver-driver-did-echo.name" . }}
    chart: {{ template "uni-resolver-driver-did-echo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
{{ toYaml .Values.env | indent 2 }}
